### ISSUE TITLE
Type inference failures

### ISSUE THREAD

**Issue by AzamatB** [under-Peter/OMEinsum.jl#92]
I'm seeing that in my code, all of the uses of `einsum` from this package are getting inferred as `Any`, which propagates and infects _all of my code_, making it slow and defeating the purpose of using this package as the speed was the primary reason for me to use `OMEinsum` in a first place.

Here are the minimum reproducible examples, derived from my actual code:
```Julia
f1(x, y) = @ein z[i,k,l] := x[i,j] * y[j,k,l]
f2(x, y) = @ein z[i,k,l] := x[i,j] * y[k,j,l]
f3(x, y) = @ein z[k,j] := x[i,j] * y[i,k,j]
f4(x, y) = @ein z[k,j] := x[i,j] * y[k,i,j]
f5(x, y) = @ein z[j,k] := x[i] * y[i,j,k]
f6(x, y) = @ein z[i,k] := y[i,j,k] * x[j,k]
```
and here is the results of running `@code_warntype` on these functions:
```Julia
julia> x = rand(3, 5);

julia> y = rand(5, 11, 7);

julia> @code_warntype f1(x, y)
Variables
  #self#::Core.Compiler.Const(f1, false)
  x::Array{Float64,2}
  y::Array{Float64,3}
  z::Any

Body::Any
1 ─ %1 = Core.tuple((1, 2), (2, 3, 4))::Core.Compiler.Const(((1, 2), (2, 3, 4)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (1, 3, 4))::Core.Compiler.Const(EinCode{((1, 2), (2, 3, 4)),(1, 3, 4)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2), (2, 3, 4)),(1, 3, 4)}(), false)
│   %4 = Core.tuple(x, y)::Tuple{Array{Float64,2},Array{Float64,3}}
│   %5 = OMEinsum.einsum(%3, %4)::Any
│        (z = %5)
└──      return %5

julia> y = rand(11, 5, 7);

julia> @code_warntype f2(x, y)
Variables
  #self#::Core.Compiler.Const(f2, false)
  x::Array{Float64,2}
  y::Array{Float64,3}
  z::Any

Body::Any
1 ─ %1 = Core.tuple((1, 2), (3, 2, 4))::Core.Compiler.Const(((1, 2), (3, 2, 4)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (1, 3, 4))::Core.Compiler.Const(EinCode{((1, 2), (3, 2, 4)),(1, 3, 4)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2), (3, 2, 4)),(1, 3, 4)}(), false)
│   %4 = Core.tuple(x, y)::Tuple{Array{Float64,2},Array{Float64,3}}
│   %5 = OMEinsum.einsum(%3, %4)::Any
│        (z = %5)
└──      return %5

julia> y = rand(3, 7, 5);

julia> @code_warntype f3(x, y)
Variables
  #self#::Core.Compiler.Const(f3, false)
  x::Array{Float64,2}
  y::Array{Float64,3}
  z::Any

Body::Any
1 ─ %1 = Core.tuple((1, 2), (1, 3, 2))::Core.Compiler.Const(((1, 2), (1, 3, 2)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (3, 2))::Core.Compiler.Const(EinCode{((1, 2), (1, 3, 2)),(3, 2)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2), (1, 3, 2)),(3, 2)}(), false)
│   %4 = Core.tuple(x, y)::Tuple{Array{Float64,2},Array{Float64,3}}
│   %5 = OMEinsum.einsum(%3, %4)::Any
│        (z = %5)
└──      return %5

julia> y = rand(7, 3, 5);

julia> @code_warntype f4(x, y)
Variables
  #self#::Core.Compiler.Const(f4, false)
  x::Array{Float64,2}
  y::Array{Float64,3}
  z::Any

Body::Any
1 ─ %1 = Core.tuple((1, 2), (3, 1, 2))::Core.Compiler.Const(((1, 2), (3, 1, 2)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (3, 2))::Core.Compiler.Const(EinCode{((1, 2), (3, 1, 2)),(3, 2)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2), (3, 1, 2)),(3, 2)}(), false)
│   %4 = Core.tuple(x, y)::Tuple{Array{Float64,2},Array{Float64,3}}
│   %5 = OMEinsum.einsum(%3, %4)::Any
│        (z = %5)
└──      return %5

julia> x = rand(7);

julia> @code_warntype f5(x, y)
Variables
  #self#::Core.Compiler.Const(f5, false)
  x::Array{Float64,1}
  y::Array{Float64,3}
  z::Any

Body::Any
1 ─ %1 = Core.tuple((1,), (1, 2, 3))::Core.Compiler.Const(((1,), (1, 2, 3)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (2, 3))::Core.Compiler.Const(EinCode{((1,), (1, 2, 3)),(2, 3)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1,), (1, 2, 3)),(2, 3)}(), false)
│   %4 = Core.tuple(x, y)::Tuple{Array{Float64,1},Array{Float64,3}}
│   %5 = OMEinsum.einsum(%3, %4)::Any
│        (z = %5)
└──      return %5

julia> x = rand(3, 5);

julia> @code_warntype f6(x, y)
Variables
  #self#::Core.Compiler.Const(f6, false)
  x::Array{Float64,2}
  y::Array{Float64,3}
  z::Any

Body::Any
1 ─ %1 = Core.tuple((1, 2, 3), (2, 3))::Core.Compiler.Const(((1, 2, 3), (2, 3)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (1, 3))::Core.Compiler.Const(EinCode{((1, 2, 3), (2, 3)),(1, 3)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2, 3), (2, 3)),(1, 3)}(), false)
│   %4 = Core.tuple(y, x)::Tuple{Array{Float64,3},Array{Float64,2}}
│   %5 = OMEinsum.einsum(%3, %4)::Any
│        (z = %5)
└──      return %5
```
as you can see in all outputs are inferred as `Any`.
Is it possible to fix this?

**Comment by mcabbott** [comment]
This could also explain the terrible performance in [this thread](https://discourse.julialang.org/t/non-matching-indices-error-using-tensoroperations/35136):
```julia
julia> using Einsum, OMEinsum, TensorCast

julia> f_ome(a,b) = @ein c[k, n] := a[k, n, c] * conj(b)[c,k];

julia> f_cast(a,b) = @reduce c[k, n] := sum(l) a[k, n, l] * b[l, k]';

julia> f_ein(a,b) = @einsum c_[k, n] := a[k, n, c] * conj(b[c,k]);

julia> a = randn(ComplexF64, 300, 400, 500); b = randn(ComplexF64, 500, 300);

julia> f_ome(a,b) ≈ f_cast(a,b) ≈ f_ein(a,b)
true

julia> @btime f_ome($a, $b);
  1.829 s (249 allocations: 921.49 MiB)

julia> @btime f_cast($a, $b);
  538.463 ms (26 allocations: 919.65 MiB)

julia> @btime f_ein($a, $b);
  254.324 ms (2 allocations: 1.83 MiB)

julia> @code_warntype f_ome(a, b)
Variables
  #self#::Core.Compiler.Const(f_ome, false)
  a::Array{Complex{Float64},3}
  b::Array{Complex{Float64},2}
  c::Any

Body::Any
1 ─ %1 = Core.tuple((1, 2, 3), (3, 1))::Core.Compiler.Const(((1, 2, 3), (3, 1)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (1, 2))::Core.Compiler.Const(EinCode{((1, 2, 3), (3, 1)),(1, 2)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2, 3), (3, 1)),(1, 2)}(), false)
│   %4 = Main.conj(b)::Array{Complex{Float64},2}
│   %5 = Core.tuple(a, %4)::Tuple{Array{Complex{Float64},3},Array{Complex{Float64},2}}
│   %6 = OMEinsum.einsum(%3, %5)::Any
│        (c = %6)
└──      return %6
```

**Comment by GiggleLiu** [comment]
Well, the copy is very slow.
When entering `batched_gemm`, copy is required.
This explains most overheads. Hmm, this is not an issue that can be easily fixed. Any idea?

```julia repl
julia> @benchmark copy(a)
BenchmarkTools.Trial: 
  memory estimate:  915.53 MiB
  allocs estimate:  2
  --------------
  minimum time:     577.359 ms (0.20% GC)
  median time:      638.778 ms (10.30% GC)
  mean time:        644.303 ms (10.06% GC)
  maximum time:     752.103 ms (23.32% GC)
  --------------
  samples:          8
  evals/sample:     1

julia> f_ome(a,b) = @ein c[n, k] := a[n, c, k] * conj(b)[c, k];

julia> @btime f_ome($a, $b);
  104.499 ms (25 allocations: 5.34 MiB)

julia> f_cast(a,b) = @reduce c[n, k] := sum(l) a[n, l, k] * b[l, k]';

julia> @btime f_cast($a, $b);
  621.662 ms (25 allocations: 918.58 MiB)
```

**Comment by Roger-luo** [comment]
It'd be clear if anyone could show the actual call to einsum function.

**Comment by GiggleLiu** [comment]
@Roger-luo

See the above profile.

**Comment by mcabbott** [comment]
Indeed, I guess 1 second is implausible for one type instability too. I hadn't got around to profiling it. But `permutedims` is indeed super-slow. I thought Strided.jl had a faster tiled method, but perhaps I mis-remember. But it can be done faster, for sure:
```julia
julia> @btime permutedims($a, (2,3,1));
  1.737 s (6 allocations: 915.53 MiB)

julia> using Strided

julia> @btime @strided permutedims($a, (2,3,1));
  43.606 ns (3 allocations: 160 bytes)

julia> @btime collect(@strided permutedims($a, (2,3,1)));
  1.725 s (5 allocations: 915.53 MiB)

julia> using Tullio 

julia> p_tul(a) = @tullio a_[n, c, k] := a[k, n, c]  {tile, thread};

julia> p_tul(a) ≈ permutedims(a, (2,3,1))
true

julia> @btime p_tul($a);
  547.626 ms (28 allocations: 918.28 MiB)

julia> f_tul(a,b) = @tullio c_[k, n] := a[k, n, c] * conj(b[c,k])  {tile, thread};

julia> f_tul(a, b) ≈ f_ein(a, b)
true

julia> @btime f_tul($a, $b);
  142.982 ms (27 allocations: 1.84 MiB)
```

**Comment by GiggleLiu** [comment]
```julia repl
julia> a = randn(ComplexF64, 300, 400, 500); b = randn(ComplexF64, 500, 300);

julia> @btime f_ome($a, $b);
  2.219 s (36 allocations: 921.94 MiB)
```

The new benchmark with `@strided` shows no advantage.
`@strided` returns a `StridedView`, is it possible to add the support to it in your `BatchedRoutines`? @Roger-luo

**Comment by mcabbott** [comment]
Right, `StridedView` is more-or-less a different implementation of `PermutedDimsArray`. Which does have `strides` that could perhaps be used? Perhaps for most cases, except the one where the batch index is leftmost?

The fallback routine in `NNlib` is happy to take `PermutedDimsArray`, and modulo some mistakes gives me:
```julia
julia> using NNlib

julia> @btime f_nnlib($a, $b);
  1.142 s (2755 allocations: 1.99 MiB)
```

**Comment by GiggleLiu** [comment]
@mcabbott Since BatchedRoutines does not support this type yet, we coverted the input to `Array` in OMEinsum, this explains why it is still low. It should definitely support it according to your examples.

**Comment by mcabbott** [comment]
BTW, I think that Nvidia has a strided_batched_gemm which allows all cases, including this one, but (IIRC) CuArrays is presently only hooked up for certain strides. 

And perhaps the other lesson is that Julia's `permutedims` ought to be much quicker.

**Comment by mcabbott** [comment]
Progress:
```julia
julia> using TensorOperations

julia> tensorcopy(a, (1,2,3), (2,3,1)) == permutedims(a, (2,3,1))
true

julia> @btime tensorcopy($a, (1,2,3), (2,3,1));
  316.898 ms (41 allocations: 915.53 MiB)

julia> @btime f_ome($a, $b); # using that
  387.190 ms (329 allocations: 921.50 MiB)
```

**Comment by GiggleLiu** [comment]
Thanks @mcabbott , we should definitely switch to using `tensorcopy`.

since the type inference problem has been fixed by #93 , we can move to #94 to continue our discussion.

**Comment by AzamatB** [comment]
It looks like the examples above are is still not working for `CuArrays`:
```Julia
using Flux
using CuArrays

julia> x = gpu(rand(3, 5));

julia> y = gpu(rand(5, 11, 7));

julia> @code_warntype f1(x, y)
Variables
  #self#::Core.Compiler.Const(f1, false)
  x::CuArray{Float32,2,Nothing}
  y::CuArray{Float32,3,Nothing}
  z::Union{CuArray{Float32,3,Nothing}, CuArray{Float32,3,CuArray{Float32,3,Nothing}}}

Body::Union{CuArray{Float32,3,Nothing}, CuArray{Float32,3,CuArray{Float32,3,Nothing}}}
1 ─ %1 = Core.tuple((1, 2), (2, 3, 4))::Core.Compiler.Const(((1, 2), (2, 3, 4)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (1, 3, 4))::Core.Compiler.Const(EinCode{((1, 2), (2, 3, 4)),(1, 3, 4)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2), (2, 3, 4)),(1, 3, 4)}(), false)
│   %4 = Core.tuple(x, y)::Tuple{CuArray{Float32,2,Nothing},CuArray{Float32,3,Nothing}}
│   %5 = OMEinsum.einsum(%3, %4)::Union{CuArray{Float32,3,Nothing}, CuArray{Float32,3,CuArray{Float32,3,Nothing}}}
│        (z = %5)
└──      return %5

julia> y = gpu(rand(11, 5, 7));

julia> @code_warntype f2(x, y)
Variables
  #self#::Core.Compiler.Const(f2, false)
  x::CuArray{Float32,2,Nothing}
  y::CuArray{Float32,3,Nothing}
  z::Union{CuArray{Float32,3,Nothing}, CuArray{Float32,3,CuArray{Float32,3,Nothing}}}

Body::Union{CuArray{Float32,3,Nothing}, CuArray{Float32,3,CuArray{Float32,3,Nothing}}}
1 ─ %1 = Core.tuple((1, 2), (3, 2, 4))::Core.Compiler.Const(((1, 2), (3, 2, 4)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (1, 3, 4))::Core.Compiler.Const(EinCode{((1, 2), (3, 2, 4)),(1, 3, 4)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2), (3, 2, 4)),(1, 3, 4)}(), false)
│   %4 = Core.tuple(x, y)::Tuple{CuArray{Float32,2,Nothing},CuArray{Float32,3,Nothing}}
│   %5 = OMEinsum.einsum(%3, %4)::Union{CuArray{Float32,3,Nothing}, CuArray{Float32,3,CuArray{Float32,3,Nothing}}}
│        (z = %5)
└──      return %5

julia> y = gpu(rand(3, 7, 5));

julia> @code_warntype f3(x, y)
Variables
  #self#::Core.Compiler.Const(f3, false)
  x::CuArray{Float32,2,Nothing}
  y::CuArray{Float32,3,Nothing}
  z::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}

Body::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}
1 ─ %1 = Core.tuple((1, 2), (1, 3, 2))::Core.Compiler.Const(((1, 2), (1, 3, 2)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (3, 2))::Core.Compiler.Const(EinCode{((1, 2), (1, 3, 2)),(3, 2)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2), (1, 3, 2)),(3, 2)}(), false)
│   %4 = Core.tuple(x, y)::Tuple{CuArray{Float32,2,Nothing},CuArray{Float32,3,Nothing}}
│   %5 = OMEinsum.einsum(%3, %4)::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}
│        (z = %5)
└──      return %5

julia> y = gpu(rand(7, 3, 5));

julia> @code_warntype f4(x, y)
Variables
  #self#::Core.Compiler.Const(f4, false)
  x::CuArray{Float32,2,Nothing}
  y::CuArray{Float32,3,Nothing}
  z::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}

Body::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}
1 ─ %1 = Core.tuple((1, 2), (3, 1, 2))::Core.Compiler.Const(((1, 2), (3, 1, 2)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (3, 2))::Core.Compiler.Const(EinCode{((1, 2), (3, 1, 2)),(3, 2)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2), (3, 1, 2)),(3, 2)}(), false)
│   %4 = Core.tuple(x, y)::Tuple{CuArray{Float32,2,Nothing},CuArray{Float32,3,Nothing}}
│   %5 = OMEinsum.einsum(%3, %4)::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}
│        (z = %5)
└──      return %5

julia> x = gpu(rand(7));

julia> @code_warntype f5(x, y)
Variables
  #self#::Core.Compiler.Const(f5, false)
  x::CuArray{Float32,1,Nothing}
  y::CuArray{Float32,3,Nothing}
  z::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}

Body::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}
1 ─ %1 = Core.tuple((1,), (1, 2, 3))::Core.Compiler.Const(((1,), (1, 2, 3)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (2, 3))::Core.Compiler.Const(EinCode{((1,), (1, 2, 3)),(2, 3)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1,), (1, 2, 3)),(2, 3)}(), false)
│   %4 = Core.tuple(x, y)::Tuple{CuArray{Float32,1,Nothing},CuArray{Float32,3,Nothing}}
│   %5 = OMEinsum.einsum(%3, %4)::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}
│        (z = %5)
└──      return %5

julia> x = gpu(rand(3, 5));

julia> @code_warntype f6(x, y)
Variables
  #self#::Core.Compiler.Const(f6, false)
  x::CuArray{Float32,2,Nothing}
  y::CuArray{Float32,3,Nothing}
  z::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}

Body::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}
1 ─ %1 = Core.tuple((1, 2, 3), (2, 3))::Core.Compiler.Const(((1, 2, 3), (2, 3)), false)
│   %2 = Core.apply_type(OMEinsum.EinCode, %1, (1, 3))::Core.Compiler.Const(EinCode{((1, 2, 3), (2, 3)),(1, 3)}, false)
│   %3 = (%2)()::Core.Compiler.Const(EinCode{((1, 2, 3), (2, 3)),(1, 3)}(), false)
│   %4 = Core.tuple(y, x)::Tuple{CuArray{Float32,3,Nothing},CuArray{Float32,2,Nothing}}
│   %5 = OMEinsum.einsum(%3, %4)::Union{CuArray{Float32,2,Nothing}, CuArray{Float32,2,CuArray{Float32,3,Nothing}}}
│        (z = %5)
└──      return %5
```
